server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          client-server-oidc:
            provider: spring
            client-id: clientTeste
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/{registrationId}
            scope: openid, USER, ADMIN
            client-name: client-server-oidc
        provider:
          spring:
            issuer-uri: http://localhost:9000
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo